version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - LOCALSTACK_TMPDIR=/var/lib/localstack/tmp
    volumes:
      - "./localstack-data:/var/lib/localstack"   # persistent state
      - "/var/run/docker.sock:/var/run/docker.sock"
